insert into sessions (experimenter_id, name, num_periods, num_traders, open_delay, session_status, def) values('1', 'test_2_traders', '3', '0', '10', '2', '<session>
  <name>test_2_traders</name>
  <periods>
    <periodDef>
      <marketEngine>continuous</marketEngine>
      <groups>
        <periodGroup>
          <id>0</id>
          <name>Red</name>
          <cashInitial>1000.0</cashInitial>
          <payoffFunctionName>GenericPayoff Spec 0</payoffFunctionName>
          <bankruptcyFunctionName>GenericBankruptcy Spec 0</bankruptcyFunctionName>
          <bankruptcyCutoff>0.0</bankruptcyCutoff>
          <addCash>false</addCash>
        </periodGroup>
        <periodGroup>
          <id>1</id>
          <name>Blue</name>
          <cashInitial>1000.0</cashInitial>
          <payoffFunctionName>GenericPayoff Spec 0</payoffFunctionName>
          <bankruptcyFunctionName>GenericBankruptcy Spec 0</bankruptcyFunctionName>
          <bankruptcyCutoff>0.0</bankruptcyCutoff>
          <addCash>false</addCash>
        </periodGroup>
      </groups>
      <securities>
        <periodSecurity>
          <title>MS</title>
          <minPrice>0.0</minPrice>
          <maxPrice>30.0</maxPrice>
          <timeOpen>120</timeOpen>
          <addDividend>
            <boolean>false</boolean>
            <boolean>false</boolean>
          </addDividend>
          <addSurplus>
            <boolean>true</boolean>
            <boolean>true</boolean>
          </addSurplus>
          <initials>
            <int>10</int>
            <int>10</int>
          </initials>
          <constraints>
            <int>10</int>
            <int>10</int>
          </constraints>
          <buyPriveleges>
            <boolean>true</boolean>
            <boolean>true</boolean>
          </buyPriveleges>
          <sellPriveleges>
            <boolean>true</boolean>
            <boolean>true</boolean>
          </sellPriveleges>
        </periodSecurity>
        <periodSecurity>
          <title>APPLE</title>
          <minPrice>0.0</minPrice>
          <maxPrice>50.0</maxPrice>
          <timeOpen>120</timeOpen>
          <addDividend>
            <boolean>false</boolean>
            <boolean>false</boolean>
          </addDividend>
          <addSurplus>
            <boolean>false</boolean>
            <boolean>false</boolean>
          </addSurplus>
          <initials>
            <int>10</int>
            <int>10</int>
          </initials>
          <constraints>
            <int>10</int>
            <int>0</int>
          </constraints>
          <buyPriveleges>
            <boolean>true</boolean>
            <boolean>true</boolean>
          </buyPriveleges>
          <sellPriveleges>
            <boolean>true</boolean>
            <boolean>true</boolean>
          </sellPriveleges>
        </periodSecurity>
        <periodSecurity>
          <title>GOOG</title>
          <minPrice>0.0</minPrice>
          <maxPrice>600.0</maxPrice>
          <timeOpen>120</timeOpen>
          <addDividend>
            <boolean>false</boolean>
            <boolean>false</boolean>
          </addDividend>
          <addSurplus>
            <boolean>true</boolean>
            <boolean>true</boolean>
          </addSurplus>
          <initials>
            <int>10</int>
            <int>10</int>
          </initials>
          <constraints>
            <int>0</int>
            <int>10</int>
          </constraints>
          <buyPriveleges>
            <boolean>true</boolean>
            <boolean>true</boolean>
          </buyPriveleges>
          <sellPriveleges>
            <boolean>true</boolean>
            <boolean>true</boolean>
          </sellPriveleges>
        </periodSecurity>
      </securities>
      <subjects>
        <periodSubject>
          <id>0</id>
          <group>0</group>
        </periodSubject>
        <periodSubject>
          <id>1</id>
          <group>1</group>
        </periodSubject>
      </subjects>
      <numSecurities>3</numSecurities>
      <numDivisions>11</numDivisions>
      <numStates>3</numStates>
      <id>0</id>
      <openDelay>5</openDelay>
      <periodLength>120</periodLength>
      <payoffFunctionSpecs>
        <payoffFunction>
          <name>GenericPayoff</name>
          <specName>GenericPayoff Spec 0</specName>
          <payoffFunction class="edu.caltechUcla.sselCassel.projects.jMarkets.shared.functions.GenericPayoffFunction">
            <securityPayoffs>
              <float>100.0</float>
              <float>90.0</float>
              <float>120.0</float>
              <float>1.0</float>
            </securityPayoffs>
            <fields>
              <string>Period_Security_Payoff_0</string>
              <string>Period_Security_Payoff_1</string>
              <string>Period_Security_Payoff_2</string>
              <string>Cash_ExchangeRate</string>
            </fields>
          </payoffFunction>
          <fieldNames>
            <string>Period_Security_Payoff_0</string>
            <string>Period_Security_Payoff_1</string>
            <string>Period_Security_Payoff_2</string>
            <string>Cash_ExchangeRate</string>
          </fieldNames>
          <fieldValues>
            <payoffSecurity>
              <stateValues>
                <string>100</string>
                <string>80</string>
                <string>120</string>
              </stateValues>
            </payoffSecurity>
            <payoffSecurity>
              <stateValues>
                <string>90</string>
                <string>100</string>
                <string>120</string>
              </stateValues>
            </payoffSecurity>
            <payoffSecurity>
              <stateValues>
                <string>120</string>
                <string>100</string>
                <string>80</string>
              </stateValues>
            </payoffSecurity>
            <payoffSecurity>
              <stateValues>
                <string>1</string>
                <string>1</string>
                <string>1</string>
              </stateValues>
            </payoffSecurity>
          </fieldValues>
        </payoffFunction>
      </payoffFunctionSpecs>
      <bankruptcyFunctionSpecs>
        <bankruptcyFunction>
          <name>GenericBankruptcy</name>
          <specName>GenericBankruptcy Spec 0</specName>
          <bankruptcyFunction class="edu.caltechUcla.sselCassel.projects.jMarkets.shared.functions.GenericBankruptcyFunction">
            <securityPayoffs>
              <float-array>
                <float>100.0</float>
                <float>80.0</float>
                <float>120.0</float>
              </float-array>
              <float-array>
                <float>90.0</float>
                <float>100.0</float>
                <float>120.0</float>
              </float-array>
              <float-array>
                <float>120.0</float>
                <float>100.0</float>
                <float>80.0</float>
              </float-array>
              <float-array>
                <float>1.0</float>
                <float>1.0</float>
                <float>1.0</float>
              </float-array>
            </securityPayoffs>
            <fields>
              <string>Security 0</string>
              <string>Security 1</string>
              <string>Security 2</string>
              <string>Cash</string>
            </fields>
            <numOfSecurities>3</numOfSecurities>
            <numOfStates>3</numOfStates>
          </bankruptcyFunction>
          <fieldNames>
            <string>Security 0</string>
            <string>Security 1</string>
            <string>Security 2</string>
            <string>Cash</string>
          </fieldNames>
          <fieldValues>
            <bankruptcySecurity>
              <stateValues>
                <string>100</string>
                <string>80</string>
                <string>120</string>
              </stateValues>
            </bankruptcySecurity>
            <bankruptcySecurity>
              <stateValues>
                <string>90</string>
                <string>100</string>
                <string>120</string>
              </stateValues>
            </bankruptcySecurity>
            <bankruptcySecurity>
              <stateValues>
                <string>120</string>
                <string>100</string>
                <string>80</string>
              </stateValues>
            </bankruptcySecurity>
            <bankruptcySecurity>
              <stateValues>
                <string>1</string>
                <string>1</string>
                <string>1</string>
              </stateValues>
            </bankruptcySecurity>
          </fieldValues>
        </bankruptcyFunction>
      </bankruptcyFunctionSpecs>
    </periodDef>
    <periodDef>
      <marketEngine>continuous</marketEngine>
      <groups>
        <periodGroup>
          <id>0</id>
          <name>Red</name>
          <cashInitial>1000.0</cashInitial>
          <payoffFunctionName>GenericPayoff Spec 0</payoffFunctionName>
          <bankruptcyFunctionName>GenericBankruptcy Spec 0</bankruptcyFunctionName>
          <bankruptcyCutoff>0.0</bankruptcyCutoff>
          <addCash>false</addCash>
        </periodGroup>
        <periodGroup>
          <id>1</id>
          <name>Blue</name>
          <cashInitial>1000.0</cashInitial>
          <payoffFunctionName>GenericPayoff Spec 0</payoffFunctionName>
          <bankruptcyFunctionName>GenericBankruptcy Spec 0</bankruptcyFunctionName>
          <bankruptcyCutoff>0.0</bankruptcyCutoff>
          <addCash>false</addCash>
        </periodGroup>
      </groups>
      <securities>
        <periodSecurity>
          <title>MS</title>
          <minPrice>0.0</minPrice>
          <maxPrice>30.0</maxPrice>
          <timeOpen>120</timeOpen>
          <addDividend>
            <boolean>false</boolean>
            <boolean>false</boolean>
          </addDividend>
          <addSurplus>
            <boolean>true</boolean>
            <boolean>true</boolean>
          </addSurplus>
          <initials>
            <int>10</int>
            <int>10</int>
          </initials>
          <constraints>
            <int>10</int>
            <int>10</int>
          </constraints>
          <buyPriveleges>
            <boolean>true</boolean>
            <boolean>true</boolean>
          </buyPriveleges>
          <sellPriveleges>
            <boolean>true</boolean>
            <boolean>true</boolean>
          </sellPriveleges>
        </periodSecurity>
        <periodSecurity>
          <title>APPLE</title>
          <minPrice>0.0</minPrice>
          <maxPrice>50.0</maxPrice>
          <timeOpen>120</timeOpen>
          <addDividend>
            <boolean>false</boolean>
            <boolean>false</boolean>
          </addDividend>
          <addSurplus>
            <boolean>false</boolean>
            <boolean>false</boolean>
          </addSurplus>
          <initials>
            <int>10</int>
            <int>10</int>
          </initials>
          <constraints>
            <int>10</int>
            <int>0</int>
          </constraints>
          <buyPriveleges>
            <boolean>true</boolean>
            <boolean>true</boolean>
          </buyPriveleges>
          <sellPriveleges>
            <boolean>true</boolean>
            <boolean>true</boolean>
          </sellPriveleges>
        </periodSecurity>
        <periodSecurity>
          <title>GOOG</title>
          <minPrice>0.0</minPrice>
          <maxPrice>600.0</maxPrice>
          <timeOpen>120</timeOpen>
          <addDividend>
            <boolean>false</boolean>
            <boolean>false</boolean>
          </addDividend>
          <addSurplus>
            <boolean>true</boolean>
            <boolean>true</boolean>
          </addSurplus>
          <initials>
            <int>10</int>
            <int>10</int>
          </initials>
          <constraints>
            <int>0</int>
            <int>10</int>
          </constraints>
          <buyPriveleges>
            <boolean>true</boolean>
            <boolean>true</boolean>
          </buyPriveleges>
          <sellPriveleges>
            <boolean>true</boolean>
            <boolean>true</boolean>
          </sellPriveleges>
        </periodSecurity>
      </securities>
      <subjects>
        <periodSubject>
          <id>0</id>
          <group>0</group>
        </periodSubject>
        <periodSubject>
          <id>1</id>
          <group>1</group>
        </periodSubject>
      </subjects>
      <numSecurities>3</numSecurities>
      <numDivisions>11</numDivisions>
      <numStates>3</numStates>
      <id>1</id>
      <openDelay>5</openDelay>
      <periodLength>120</periodLength>
      <payoffFunctionSpecs>
        <payoffFunction>
          <name>GenericPayoff</name>
          <specName>GenericPayoff Spec 0</specName>
          <payoffFunction class="edu.caltechUcla.sselCassel.projects.jMarkets.shared.functions.GenericPayoffFunction">
            <securityPayoffs>
              <float>100.0</float>
              <float>90.0</float>
              <float>120.0</float>
              <float>1.0</float>
            </securityPayoffs>
            <fields>
              <string>Period_Security_Payoff_0</string>
              <string>Period_Security_Payoff_1</string>
              <string>Period_Security_Payoff_2</string>
              <string>Cash_ExchangeRate</string>
            </fields>
          </payoffFunction>
          <fieldNames>
            <string>Period_Security_Payoff_0</string>
            <string>Period_Security_Payoff_1</string>
            <string>Period_Security_Payoff_2</string>
            <string>Cash_ExchangeRate</string>
          </fieldNames>
          <fieldValues>
            <payoffSecurity>
              <stateValues>
                <string>100</string>
                <string>80</string>
                <string>120</string>
              </stateValues>
            </payoffSecurity>
            <payoffSecurity>
              <stateValues>
                <string>90</string>
                <string>100</string>
                <string>120</string>
              </stateValues>
            </payoffSecurity>
            <payoffSecurity>
              <stateValues>
                <string>120</string>
                <string>100</string>
                <string>80</string>
              </stateValues>
            </payoffSecurity>
            <payoffSecurity>
              <stateValues>
                <string>1</string>
                <string>1</string>
                <string>1</string>
              </stateValues>
            </payoffSecurity>
          </fieldValues>
        </payoffFunction>
      </payoffFunctionSpecs>
      <bankruptcyFunctionSpecs>
        <bankruptcyFunction>
          <name>GenericBankruptcy</name>
          <specName>GenericBankruptcy Spec 0</specName>
          <bankruptcyFunction class="edu.caltechUcla.sselCassel.projects.jMarkets.shared.functions.GenericBankruptcyFunction">
            <securityPayoffs>
              <float-array>
                <float>100.0</float>
                <float>80.0</float>
                <float>120.0</float>
              </float-array>
              <float-array>
                <float>90.0</float>
                <float>100.0</float>
                <float>120.0</float>
              </float-array>
              <float-array>
                <float>120.0</float>
                <float>100.0</float>
                <float>80.0</float>
              </float-array>
              <float-array>
                <float>1.0</float>
                <float>1.0</float>
                <float>1.0</float>
              </float-array>
            </securityPayoffs>
            <fields>
              <string>Security 0</string>
              <string>Security 1</string>
              <string>Security 2</string>
              <string>Cash</string>
            </fields>
            <numOfSecurities>3</numOfSecurities>
            <numOfStates>3</numOfStates>
          </bankruptcyFunction>
          <fieldNames>
            <string>Security 0</string>
            <string>Security 1</string>
            <string>Security 2</string>
            <string>Cash</string>
          </fieldNames>
          <fieldValues>
            <bankruptcySecurity>
              <stateValues>
                <string>100</string>
                <string>80</string>
                <string>120</string>
              </stateValues>
            </bankruptcySecurity>
            <bankruptcySecurity>
              <stateValues>
                <string>90</string>
                <string>100</string>
                <string>120</string>
              </stateValues>
            </bankruptcySecurity>
            <bankruptcySecurity>
              <stateValues>
                <string>120</string>
                <string>100</string>
                <string>80</string>
              </stateValues>
            </bankruptcySecurity>
            <bankruptcySecurity>
              <stateValues>
                <string>1</string>
                <string>1</string>
                <string>1</string>
              </stateValues>
            </bankruptcySecurity>
          </fieldValues>
        </bankruptcyFunction>
      </bankruptcyFunctionSpecs>
    </periodDef>
    <periodDef>
      <marketEngine>continuous</marketEngine>
      <groups>
        <periodGroup>
          <id>0</id>
          <name>Red</name>
          <cashInitial>1000.0</cashInitial>
          <payoffFunctionName>GenericPayoff Spec 0</payoffFunctionName>
          <bankruptcyFunctionName>GenericBankruptcy Spec 0</bankruptcyFunctionName>
          <bankruptcyCutoff>0.0</bankruptcyCutoff>
          <addCash>false</addCash>
        </periodGroup>
        <periodGroup>
          <id>1</id>
          <name>Blue</name>
          <cashInitial>1000.0</cashInitial>
          <payoffFunctionName>GenericPayoff Spec 0</payoffFunctionName>
          <bankruptcyFunctionName>GenericBankruptcy Spec 0</bankruptcyFunctionName>
          <bankruptcyCutoff>0.0</bankruptcyCutoff>
          <addCash>false</addCash>
        </periodGroup>
      </groups>
      <securities>
        <periodSecurity>
          <title>MS</title>
          <minPrice>0.0</minPrice>
          <maxPrice>30.0</maxPrice>
          <timeOpen>120</timeOpen>
          <addDividend>
            <boolean>false</boolean>
            <boolean>false</boolean>
          </addDividend>
          <addSurplus>
            <boolean>true</boolean>
            <boolean>true</boolean>
          </addSurplus>
          <initials>
            <int>10</int>
            <int>10</int>
          </initials>
          <constraints>
            <int>10</int>
            <int>10</int>
          </constraints>
          <buyPriveleges>
            <boolean>true</boolean>
            <boolean>true</boolean>
          </buyPriveleges>
          <sellPriveleges>
            <boolean>true</boolean>
            <boolean>true</boolean>
          </sellPriveleges>
        </periodSecurity>
        <periodSecurity>
          <title>APPLE</title>
          <minPrice>0.0</minPrice>
          <maxPrice>50.0</maxPrice>
          <timeOpen>120</timeOpen>
          <addDividend>
            <boolean>false</boolean>
            <boolean>false</boolean>
          </addDividend>
          <addSurplus>
            <boolean>false</boolean>
            <boolean>false</boolean>
          </addSurplus>
          <initials>
            <int>10</int>
            <int>10</int>
          </initials>
          <constraints>
            <int>10</int>
            <int>0</int>
          </constraints>
          <buyPriveleges>
            <boolean>true</boolean>
            <boolean>true</boolean>
          </buyPriveleges>
          <sellPriveleges>
            <boolean>true</boolean>
            <boolean>true</boolean>
          </sellPriveleges>
        </periodSecurity>
        <periodSecurity>
          <title>GOOG</title>
          <minPrice>0.0</minPrice>
          <maxPrice>600.0</maxPrice>
          <timeOpen>120</timeOpen>
          <addDividend>
            <boolean>false</boolean>
            <boolean>false</boolean>
          </addDividend>
          <addSurplus>
            <boolean>true</boolean>
            <boolean>true</boolean>
          </addSurplus>
          <initials>
            <int>10</int>
            <int>10</int>
          </initials>
          <constraints>
            <int>0</int>
            <int>10</int>
          </constraints>
          <buyPriveleges>
            <boolean>true</boolean>
            <boolean>true</boolean>
          </buyPriveleges>
          <sellPriveleges>
            <boolean>true</boolean>
            <boolean>true</boolean>
          </sellPriveleges>
        </periodSecurity>
      </securities>
      <subjects>
        <periodSubject>
          <id>0</id>
          <group>0</group>
        </periodSubject>
        <periodSubject>
          <id>1</id>
          <group>1</group>
        </periodSubject>
      </subjects>
      <numSecurities>3</numSecurities>
      <numDivisions>11</numDivisions>
      <numStates>3</numStates>
      <id>2</id>
      <openDelay>5</openDelay>
      <periodLength>120</periodLength>
      <payoffFunctionSpecs>
        <payoffFunction>
          <name>GenericPayoff</name>
          <specName>GenericPayoff Spec 0</specName>
          <payoffFunction class="edu.caltechUcla.sselCassel.projects.jMarkets.shared.functions.GenericPayoffFunction">
            <securityPayoffs>
              <float>100.0</float>
              <float>90.0</float>
              <float>120.0</float>
              <float>1.0</float>
            </securityPayoffs>
            <fields>
              <string>Period_Security_Payoff_0</string>
              <string>Period_Security_Payoff_1</string>
              <string>Period_Security_Payoff_2</string>
              <string>Cash_ExchangeRate</string>
            </fields>
          </payoffFunction>
          <fieldNames>
            <string>Period_Security_Payoff_0</string>
            <string>Period_Security_Payoff_1</string>
            <string>Period_Security_Payoff_2</string>
            <string>Cash_ExchangeRate</string>
          </fieldNames>
          <fieldValues>
            <payoffSecurity>
              <stateValues>
                <string>100</string>
                <string>80</string>
                <string>120</string>
              </stateValues>
            </payoffSecurity>
            <payoffSecurity>
              <stateValues>
                <string>90</string>
                <string>100</string>
                <string>120</string>
              </stateValues>
            </payoffSecurity>
            <payoffSecurity>
              <stateValues>
                <string>120</string>
                <string>100</string>
                <string>80</string>
              </stateValues>
            </payoffSecurity>
            <payoffSecurity>
              <stateValues>
                <string>1</string>
                <string>1</string>
                <string>1</string>
              </stateValues>
            </payoffSecurity>
          </fieldValues>
        </payoffFunction>
      </payoffFunctionSpecs>
      <bankruptcyFunctionSpecs>
        <bankruptcyFunction>
          <name>GenericBankruptcy</name>
          <specName>GenericBankruptcy Spec 0</specName>
          <bankruptcyFunction class="edu.caltechUcla.sselCassel.projects.jMarkets.shared.functions.GenericBankruptcyFunction">
            <securityPayoffs>
              <float-array>
                <float>100.0</float>
                <float>80.0</float>
                <float>120.0</float>
              </float-array>
              <float-array>
                <float>90.0</float>
                <float>100.0</float>
                <float>120.0</float>
              </float-array>
              <float-array>
                <float>120.0</float>
                <float>100.0</float>
                <float>80.0</float>
              </float-array>
              <float-array>
                <float>1.0</float>
                <float>1.0</float>
                <float>1.0</float>
              </float-array>
            </securityPayoffs>
            <fields>
              <string>Security 0</string>
              <string>Security 1</string>
              <string>Security 2</string>
              <string>Cash</string>
            </fields>
            <numOfSecurities>3</numOfSecurities>
            <numOfStates>3</numOfStates>
          </bankruptcyFunction>
          <fieldNames>
            <string>Security 0</string>
            <string>Security 1</string>
            <string>Security 2</string>
            <string>Cash</string>
          </fieldNames>
          <fieldValues>
            <bankruptcySecurity>
              <stateValues>
                <string>100</string>
                <string>80</string>
                <string>120</string>
              </stateValues>
            </bankruptcySecurity>
            <bankruptcySecurity>
              <stateValues>
                <string>90</string>
                <string>100</string>
                <string>120</string>
              </stateValues>
            </bankruptcySecurity>
            <bankruptcySecurity>
              <stateValues>
                <string>120</string>
                <string>100</string>
                <string>80</string>
              </stateValues>
            </bankruptcySecurity>
            <bankruptcySecurity>
              <stateValues>
                <string>1</string>
                <string>1</string>
                <string>1</string>
              </stateValues>
            </bankruptcySecurity>
          </fieldValues>
        </bankruptcyFunction>
      </bankruptcyFunctionSpecs>
    </periodDef>
  </periods>
  <groups>
    <groupDef>
      <id>0</id>
      <name>Red</name>
    </groupDef>
    <groupDef>
      <id>1</id>
      <name>Blue</name>
    </groupDef>
  </groups>
  <numSubjects>2</numSubjects>
  <numGroups>2</numGroups>
  <timeoutLength>10</timeoutLength>
  <payoffFunctions>
    <payoffDef>
      <name>GenericPayoff</name>
      <numSpecs>1</numSpecs>
    </payoffDef>
    <payoffDef>
      <name>ParkingPayoff</name>
      <numSpecs>0</numSpecs>
    </payoffDef>
    <payoffDef>
      <name>PenalvaPayoff</name>
      <numSpecs>0</numSpecs>
    </payoffDef>
    <payoffDef>
      <name>StockBondPayoff</name>
      <numSpecs>0</numSpecs>
    </payoffDef>
    <payoffDef>
      <name>TestPayoff</name>
      <numSpecs>0</numSpecs>
    </payoffDef>
    <payoffDef>
      <name>ZeroPayoff</name>
      <numSpecs>0</numSpecs>
    </payoffDef>
  </payoffFunctions>
  <bankruptcyFunctions>
    <bankruptcyDef>
      <name>GenericBankruptcy</name>
      <numSpecs>1</numSpecs>
    </bankruptcyDef>
    <bankruptcyDef>
      <name>GenericLtdBankruptcy</name>
      <numSpecs>0</numSpecs>
    </bankruptcyDef>
    <bankruptcyDef>
      <name>StockBondBankruptcy</name>
      <numSpecs>0</numSpecs>
    </bankruptcyDef>
    <bankruptcyDef>
      <name>TestBankruptcy</name>
      <numSpecs>0</numSpecs>
    </bankruptcyDef>
  </bankruptcyFunctions>
</session>'); 