/*
 * Copyright (C) 2005-2006, <a href="http://www.ssel.caltech.edu">SSEL</a>
 * <a href="http://www.cassel.ucla.edu">CASSEL</a>, Caltech/UCLA
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
 * USA.
 *
 * Project Authors: Raj Advani, Walter M. Yuan, and Peter Bossaerts
 * Email: jmarkets@ssel.caltech.edu
 */

/*
 * InitGUI.java
 *
 * Created on March 15, 2004, 1:28 PM
 */

package edu.caltechUcla.sselCassel.projects.jMarkets.client.interfaces;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author  Raj Advani
 */
public class InitGUI extends javax.swing.JDialog {
    
    /** Creates new form InitGUI */
    public InitGUI(Frame parent, String name, String host) {
        super(parent, true);
        this.name = name;
        this.host = host;
        
        initComponents();
        centerOnScreen();
        fillFields();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        setTitle("Client Startup");
        TitlePanel = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        NamePanel = new javax.swing.JPanel();
        NameLabel = new javax.swing.JLabel();
        NameText = new javax.swing.JTextField();
        HostPanel = new javax.swing.JPanel();
        HostLabel = new javax.swing.JLabel();
        HostText = new javax.swing.JTextField();
        SubmitPanel = new javax.swing.JPanel();
        SubmitButton = new javax.swing.JButton();
        SubmitFiller = new javax.swing.JPanel();
        MenuBar = new javax.swing.JMenuBar();
        Options = new javax.swing.JMenu();
        ExitMenuItem = new javax.swing.JMenuItem();
        
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));
        
        Options.setText("Options");
        ExitMenuItem.setText("Exit");
        ExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuItemAction(evt);
            }
        });
        
        Options.add(ExitMenuItem);
        MenuBar.add(Options);
        
        setJMenuBar(MenuBar);
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        
        Title.setText("Client Information");
        Title.setForeground(java.awt.Color.black);
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setFont(new java.awt.Font("Book Antiqua", 1, 24));
        TitlePanel.add(Title);
        
        getContentPane().add(TitlePanel);
        
        NameLabel.setText("Name:");
        NameLabel.setForeground(java.awt.Color.black);
        NameLabel.setFont(new java.awt.Font("Dialog", 1, 14));
        NamePanel.add(NameLabel);
        
        NameText.setFont(new java.awt.Font("Dialog", 0, 14));
        NameText.setPreferredSize(new java.awt.Dimension(200, 21));
        NamePanel.add(NameText);
        
        getContentPane().add(NamePanel);
        
        HostLabel.setText("Host:");
        HostLabel.setForeground(java.awt.Color.black);
        HostLabel.setFont(new java.awt.Font("Dialog", 1, 14));
        HostLabel.setPreferredSize(new java.awt.Dimension(43, 20));
        HostLabel.setMinimumSize(new java.awt.Dimension(43, 20));
        HostLabel.setMaximumSize(new java.awt.Dimension(43, 20));
        HostPanel.add(HostLabel);
        
        HostText.setFont(new java.awt.Font("Dialog", 0, 14));
        HostText.setPreferredSize(new java.awt.Dimension(200, 21));
        HostPanel.add(HostText);
        
        getContentPane().add(HostPanel);
        
        SubmitPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonAction(evt);
            }
        });
        
        SubmitPanel.add(SubmitButton);
        
        SubmitFiller.setPreferredSize(new java.awt.Dimension(64, 10));
        SubmitPanel.add(SubmitFiller);
        
        getContentPane().add(SubmitPanel);
        
        pack();
    }
    
    private void ExitMenuItemAction(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }
    
    private void SubmitButtonAction(java.awt.event.ActionEvent evt) {
        try{
            name = NameText.getText();
            host = HostText.getText();
            if (name == null || name.length() < 1)
                JOptionPane.showMessageDialog(null, "You must enter a valid name to proceed", "Input Error", JOptionPane.ERROR_MESSAGE);
            else if (host == null || host.length() <1)
                JOptionPane.showMessageDialog(null, "You must enter a valid host to proceed", "Input Error", JOptionPane.ERROR_MESSAGE);
            else {
                setVisible(false);
            }
        }catch(Exception e) {
            //log.error("Failed to get the client information");
        }
    }
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {
        System.exit(0);
    }
    
    
    /** Enable or disable the host and name fields depending on if they were
     *  automatically generated or not. If both were automatically generated,
     *  then automatically submit the client */
    public void fillFields() {
        if (host != null) {
            HostText.setText(host);
            HostText.setEnabled(false);    
        }
        if (name != null) {
            NameText.setText(name);
            NameText.setEnabled(false);
        }
        
        this.setVisible(true);
        
        if (!HostText.isEnabled() && !NameText.isEnabled())
            autoSubmit();
    }
    
    /** Wait a few seconds then submit automatically. Don't wait a few seconds if
     *  this is an integrated test */
    private synchronized void autoSubmit() {
        try{      
            Runnable doUpdate = new Runnable() {
                public void run() {
                    SubmitButtonAction(null);
                }
            };
            SwingUtilities.invokeLater(doUpdate);
        }catch(Exception e) {
        }
    }
    
    /* Center on the screen */
    public void centerOnScreen() {
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension window = this.getSize();
        int iCenterX = screen.width / 2;
        int iCenterY = screen.height / 2;
        setLocation(iCenterX - (window.width / 2),
        iCenterY - (window.height / 2));
    }
    
    public String getName() {
        return name;
    }
    
    public String getHost() {
        return host;
    }
    
    // Variables declaration - do not modify
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel NamePanel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameText;
    private javax.swing.JPanel HostPanel;
    private javax.swing.JLabel HostLabel;
    private javax.swing.JTextField HostText;
    private javax.swing.JPanel SubmitPanel;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JPanel SubmitFiller;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu Options;
    private javax.swing.JMenuItem ExitMenuItem;
    // End of variables declaration
    
    private long seed;
    private String mode;
    private String name;
    private String host;
    //private static Category log = Category.getInstance(InitGUI.class);
}
